# Generated by Django 3.1.1 on 2020-09-26 17:14

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0002_auto_20200925_1659"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", max_length=18
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sheets.category",
            ),
        ),
    ]
